# Generated by Django 5.0.4 on 2024-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('beds', models.FloatField()),
                ('baths', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'house_listing',
            },
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
