# Generated by Django 5.0.4 on 2024-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0003_alter_listing_baths_alter_listing_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
